package com.dsh.mobile

import com.dsh.mobile.data.modelChangedNotice
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/** 引擎的换模型说明是一整段英文方括号，手机上要压成一行中文。 */
class ModelChangedNoticeTest {

    // 手机截图里抄下来的原文（就是它显示成 4 行灰底英文）
    private val real = "[model changed: assistant turns above this point were generated by " +
        "nexavlinks/gpt-5.6-luna; the session continues with wb2api/deepseek-v4.1-flash]"

    @Test
    fun realEngineNoticeBecomesOneLine() {
        assertEquals("模型切换 · gpt-5.6-luna → deepseek-v4.1-flash", modelChangedNotice(real))
    }

    @Test
    fun handlesLineBreaks() {
        val wrapped = "[model changed: assistant turns above\nthis point were generated by nexavlinks/\ngpt-5.6-luna; the session continues with\nwb2api/deepseek-v4.1-flash]"
        assertEquals("模型切换 · gpt-5.6-luna → deepseek-v4.1-flash", modelChangedNotice(wrapped))
    }

    @Test
    fun ordinaryMessagesAreUntouched() {
        assertNull(modelChangedNotice("你好"))
        assertNull(modelChangedNotice("[model changed: 少了半截"))
        assertNull(modelChangedNotice("请把这句话翻译成英文：model changed"))
    }
}
